# EDA: Airbnb in London Q4 2025

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/raw/listings.csv')
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,13913,https://www.airbnb.com/rooms/13913,20250914034649,2025-09-16,city scrape,Holiday London DB Room Let-on going,My bright double bedroom with a large window h...,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,54730,...,4.87,4.78,4.78,NaN,f,2,1,1,0,0.30
1,15400,https://www.airbnb.com/rooms/15400,20250914034649,2025-09-16,city scrape,Bright Chelsea Apartment. Chelsea!,Lots of windows and light. St Luke's Gardens ...,It is Chelsea.,https://a0.muscache.com/pictures/428392/462d26...,60302,...,4.84,4.93,4.74,NaN,f,1,1,0,0,0.51
2,17402,https://www.airbnb.com/rooms/17402,20250914034649,2025-09-16,city scrape,Very Central Modern 3-Bed/2 Bath By Oxford St W1,"You'll have a great time in this beautiful, cl...","Fitzrovia is a very desirable trendy, arty and...",https://a0.muscache.com/pictures/39d5309d-fba7...,67564,...,4.72,4.89,4.61,NaN,f,2,2,0,0,0.32
3,24328,https://www.airbnb.com/rooms/24328,20250914034649,2025-09-18,previous scrape,Battersea live/work artist house,"Artist house by SW Battersea Park, bright high...","- Battersea is a quiet family area, easy acces...",https://a0.muscache.com/pictures/9194b40f-c627...,41759,...,4.93,4.60,4.65,NaN,f,1,1,0,0,0.53
4,36274,https://www.airbnb.com/rooms/36274,20250914034649,2025-09-15,city scrape,Bright 1 bedroom apt off brick lane in Shoreditch,*Update June '25- Pump Installed to improve wa...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,133271,...,4.46,4.85,4.54,NaN,t,2,2,0,0,0.09

## Selecting features

In [3]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='str')

In [4]:
drop_cols = ["listing_url", "scrape_id", "name",
              "neighborhood_overview","source","picture_url", "host_url", "host_id",
                "host_thumbnail_url", "host_picture_url", "estimated_occupancy_l365d", "estimated_revenue_l365d",
                 "host_location" ,"host_name", "neighbourhood_group_cleansed", "neighbourhood",
                  "availability_30", "availability_60", "availability_90", "availability_365", "availability_eoy",
                   "minimum_minimum_nights", "maximum_minimum_nights", "minimum_maximum_nights", "maximum_maximum_nights",
                   "minimum_nights_avg_ntm", "maximum_nights_avg_ntm", "calendar_updated", "calendar_last_scraped",
                   "has_availability","host_neighbourhood", "bathrooms_text",
                   "number_of_reviews_ltm", "number_of_reviews_l30d", "number_of_reviews_ly","reviews_per_month",
                   "license"]
df.drop(columns=drop_cols, inplace=True)

In [5]:
df.columns

Index(['id', 'last_scraped', 'description', 'host_since', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood_cleansed', 'latitude', 'longitude', 'property_type',
       'room_type', 'accommodates', 'bathrooms', 'bedrooms', 'beds',
       'amenities', 'price', 'minimum_nights', 'maximum_nights',
       'number_of_reviews', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms'],
      dtype='str')

In [6]:
df.head()

,id,last_scraped,description,host_since,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,13913,2025-09-16,My bright double bedroom with a large window h...,2009-11-16,I am a Multi-Media Visual Artist and Creative ...,within a few hours,100%,96%,t,2.0,...,4.80,4.81,4.87,4.78,4.78,f,2,1,1,0
1,15400,2025-09-16,Lots of windows and light. St Luke's Gardens ...,2009-12-05,"English, grandmother, I have travelled quite ...",NaN,NaN,50%,f,1.0,...,4.87,4.88,4.84,4.93,4.74,f,1,1,0,0
2,17402,2025-09-16,"You'll have a great time in this beautiful, cl...",2010-01-04,We are Liz and Jack. We manage a number of ho...,within an hour,88%,88%,t,3.0,...,4.72,4.72,4.72,4.89,4.61,f,2,2,0,0
3,24328,2025-09-18,"Artist house by SW Battersea Park, bright high...",2009-09-28,"I've been using Airbnb for a while now, both a...",within a few hours,100%,11%,f,1.0,...,4.91,4.90,4.93,4.60,4.65,f,1,1,0,0
4,36274,2025-09-15,*Update June '25- Pump Installed to improve wa...,2010-05-27,"We are Hendryks Services - your resident, mana...",within an hour,100%,98%,f,3.0,...,4.54,4.62,4.46,4.85,4.54,t,2,2,0,0

## Formating and creating features

In [7]:
df.isnull().sum()

id                                                  0
last_scraped                                        0
description                                      2450
host_since                                         41
host_about                                      47038
host_response_time                              31707
host_response_rate                              31707
host_acceptance_rate                            27760
host_is_superhost                                1766
host_listings_count                                41
host_total_listings_count                          41
host_verifications                                 41
host_has_profile_pic                               41
host_identity_verified                             41
neighbourhood_cleansed                              0
latitude                                            0
longitude                                           0
property_type                                       0
room_type                                           0
accommodates                                        0
bathrooms                                       34846
bedrooms                                        12775
beds                                            34920
amenities                                           0
price                                           34908
minimum_nights                                      0
maximum_nights                                      0
number_of_reviews                                   0
first_review                                    24122
last_review                                     24122
review_scores_rating                            24122
review_scores_accuracy                          24137
review_scores_cleanliness                       24131
review_scores_checkin                           24165
review_scores_communication                     24142
review_scores_location                          24166
review_scores_value                             24166
instant_bookable                                    0
calculated_host_listings_count                      0
calculated_host_listings_count_entire_homes         0
calculated_host_listings_count_private_rooms        0
calculated_host_listings_count_shared_rooms         0
dtype: int64

In [ ]:
#removing missing values
#df.dropna(inplace=True)
df.shape

(23665, 42)

In [9]:
# converting data types to correct types
df["host_response_time"] = df["host_response_time"].astype("category")
df["host_is_superhost"] = df["host_is_superhost"].map({"t": 1, "f": 0}).astype("int8")
df["host_identity_verified"] = df["host_identity_verified"].map({"t": 1, "f": 0}).astype("int8")
df["last_scraped"] = pd.to_datetime(df["last_scraped"])
df["host_since"] = pd.to_datetime(df["host_since"])
df["host_response_rate"] = df["host_response_rate"].str.rstrip("%").astype("float") / 100
df["price"] = df["price"].str.replace("$", "").str.replace(",", "").astype("float")
df["first_review"] = pd.to_datetime(df["first_review"])
df["last_review"] = pd.to_datetime(df["last_review"])
df["instant_bookable"] = df["instant_bookable"].map({"t": 1, "f": 0}).astype("int8")
df["host_has_profile_pic"] = df["host_has_profile_pic"].map({"t": 1, "f": 0}).astype("int8")
df["host_verificatoins"] = df["host_verifications"].apply(lambda x: len(x.strip("[]").split(", ")) if pd.notnull(x) else 0).astype("int8")
df["host_acceptance_rate"] = df["host_acceptance_rate"].str.rstrip("%").astype("float") / 100

In [10]:
df.head()

,id,last_scraped,description,host_since,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,host_verificatoins
0,13913,2025-09-16,My bright double bedroom with a large window h...,2009-11-16,I am a Multi-Media Visual Artist and Creative ...,within a few hours,1.00,0.96,1,2.0,...,4.81,4.87,4.78,4.78,0,2,1,1,0,2
2,17402,2025-09-16,"You'll have a great time in this beautiful, cl...",2010-01-04,We are Liz and Jack. We manage a number of ho...,within an hour,0.88,0.88,1,3.0,...,4.72,4.72,4.89,4.61,0,2,2,0,0,3
4,36274,2025-09-15,*Update June '25- Pump Installed to improve wa...,2010-05-27,"We are Hendryks Services - your resident, mana...",within an hour,1.00,0.98,0,3.0,...,4.62,4.46,4.85,4.54,1,2,2,0,0,2
5,36299,2025-09-15,3 Bed House with garden close to Thames river ...,2010-06-30,".Hi, I am Geert, and I've been on Airbnb both ...",within a few hours,1.00,0.91,0,1.0,...,4.94,4.96,4.90,4.65,0,1,1,0,0,3
7,38605,2025-09-15,Our guest room & bathroom overlooks the garden...,2010-07-13,We are Elisa and Dominic and we live in West L...,within a few hours,1.00,0.92,1,3.0,...,4.90,4.89,4.53,4.77,0,3,2,1,0,2

## Feature engineering

### Host features

In [11]:
df["experience"] = df["last_scraped"].dt.year - df["host_since"].dt.year

df["experience"]

0        16
2        15
4        15
5        15
7        15
         ..
96415     1
96441     9
96472    13
96481     1
96537     9
Name: experience, Length: 23665, dtype: int32

In [14]:
df["about_dummy"] = df["description"].apply(lambda x: 0 if pd.isnull(x) else 1)

df["about_dummy"].value_counts()

about_dummy
1    23665
Name: count, dtype: int64